# microProject-dev.yml
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url:  jdbc:mysql://mysql:3306/microProject?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: microProject
    # password: microProject
    hikari:
      pool-name: Hikari
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  custom:
    message: "Running in microProject DEV profile"
